// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIj_3SVGpc_Y5mprQ7w66lORpRD4kmAA',
    appId: '1:309644002856:web:bf9c0f4628ea8f107d971d',
    messagingSenderId: '309644002856',
    projectId: 'depo-bangunan-ced0b',
    authDomain: 'depo-bangunan-ced0b.firebaseapp.com',
    databaseURL: 'https://depo-bangunan-ced0b-default-rtdb.firebaseio.com',
    storageBucket: 'depo-bangunan-ced0b.appspot.com',
    measurementId: 'G-Y1KH72FLPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuyDoZgQyeeuxf7g5S1yfpkymfg_twlkQ',
    appId: '1:309644002856:android:767659483bc588077d971d',
    messagingSenderId: '309644002856',
    projectId: 'depo-bangunan-ced0b',
    databaseURL: 'https://depo-bangunan-ced0b-default-rtdb.firebaseio.com',
    storageBucket: 'depo-bangunan-ced0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvREOgvCEtPAcHhZjvZOZkSAwZCmaQ3A4',
    appId: '1:309644002856:ios:9f71d85452afeb8a7d971d',
    messagingSenderId: '309644002856',
    projectId: 'depo-bangunan-ced0b',
    databaseURL: 'https://depo-bangunan-ced0b-default-rtdb.firebaseio.com',
    storageBucket: 'depo-bangunan-ced0b.appspot.com',
    androidClientId: '309644002856-jaise2rc6or4k7fu2ek4joqdhe85v48k.apps.googleusercontent.com',
    iosClientId: '309644002856-p6mijd5mq8ndqhaublcceo1auh8p45bv.apps.googleusercontent.com',
    iosBundleId: 'com.depo.apps.antriandireksi',
  );

}