// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /* static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzvu1Hp20K26pDvMtl-oNAD33HaQ9wWCk',
    appId: '1:1026822250548:web:8d4ead40ecbd781f78aa61',
    messagingSenderId: '1026822250548',
    projectId: 'antriandireksi',
    authDomain: 'antriandireksi.firebaseapp.com',
    storageBucket: 'antriandireksi.appspot.com',
  ); */

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCIj_3SVGpc_Y5mprQ7w66lORpRD4kmAA',
    appId: '1:309644002856:web:bf9c0f4628ea8f107d971d',
    messagingSenderId: '309644002856',
    projectId: 'depo-bangunan-ced0b',
    authDomain: 'depo-bangunan-ced0b.firebaseapp.com',
    storageBucket: 'depo-bangunan-ced0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjX9GFFNCTRQmQyQUvQ45wc203UhB3-k',
    appId: '1:1026822250548:android:5b4e1a2d080b980278aa61',
    messagingSenderId: '1026822250548',
    projectId: 'antriandireksi',
    storageBucket: 'antriandireksi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkuokIr12Hn_EOz12LsCPckqvpcFOlABw',
    appId: '1:1026822250548:ios:d7929a42fccda9f878aa61',
    messagingSenderId: '1026822250548',
    projectId: 'antriandireksi',
    storageBucket: 'antriandireksi.appspot.com',
    iosBundleId: 'com.depo.apps.antriandireksi',
  );
}
