// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABOcPmzlqj7jQvuWlh0NDFU-bCQaYIBEg',
    appId: '1:781849167391:web:1a0aeab7133d5e3580b72a',
    messagingSenderId: '781849167391',
    projectId: 'antrian-direksi-ec0f3',
    authDomain: 'antrian-direksi-ec0f3.firebaseapp.com',
    storageBucket: 'antrian-direksi-ec0f3.firebasestorage.app',
    measurementId: 'G-8Y5YDHZMH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9OSmu_UNB6LqXA73Eipd6_g1kji2iBlA',
    appId: '1:781849167391:android:678a7c1379a8a31380b72a',
    messagingSenderId: '781849167391',
    projectId: 'antrian-direksi-ec0f3',
    storageBucket: 'antrian-direksi-ec0f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60_qkpuonbQGq-YqaqPLPnTItMxQOJxQ',
    appId: '1:781849167391:ios:a369f3205531626e80b72a',
    messagingSenderId: '781849167391',
    projectId: 'antrian-direksi-ec0f3',
    storageBucket: 'antrian-direksi-ec0f3.firebasestorage.app',
    iosBundleId: 'com.depo.apps.antriandireksi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60_qkpuonbQGq-YqaqPLPnTItMxQOJxQ',
    appId: '1:781849167391:ios:c2740237c10be49180b72a',
    messagingSenderId: '781849167391',
    projectId: 'antrian-direksi-ec0f3',
    storageBucket: 'antrian-direksi-ec0f3.firebasestorage.app',
    iosBundleId: 'com.depo.apps.depoAntrianDireksi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABOcPmzlqj7jQvuWlh0NDFU-bCQaYIBEg',
    appId: '1:781849167391:web:80f1e2511dd93b1080b72a',
    messagingSenderId: '781849167391',
    projectId: 'antrian-direksi-ec0f3',
    authDomain: 'antrian-direksi-ec0f3.firebaseapp.com',
    storageBucket: 'antrian-direksi-ec0f3.firebasestorage.app',
    measurementId: 'G-1SYNK8J5Y7',
  );

}